<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ns</string>
	</array>
	<key>name</key>
	<string>NitroScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\.[0-9]+|[0-9]+\.[0-9]*|[0-9]+\.?</string>
			<key>name</key>
			<string>constant.numeric.nitro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(--).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-dash.nitro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>storage.type.nitro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(this|class|var|gvar)</string>
			<key>name</key>
			<string>storage.type.nitro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return|or|else|in|by|from|to|array|pairs)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(&amp;&amp;|\|\||!)\b)|(\+|-|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.))</string>
			<key>name</key>
			<string>keyword.operator.nitro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_\.]*)\(|\(|\)</string>
			<key>name</key>
			<string>entity.name.function.nitro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_\.]*)</string>
			<key>name</key>
			<string>variable.other.nitro</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.untitled</string>
	<key>uuid</key>
	<string>CECEE09D-F0CC-4467-BAD1-3BD2590B7EF6</string>
</dict>
</plist>
